# definition of all my file paths and filter indices 
# this  makes sure the files and their filter indices are always matched (less error prone - prevent errors) (it has been checked that all paths and filter indices match!)

cell_file_paths = {
    "munich": 
        {
           "donorA": 
                        {
                            "eos": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190516_DH_WB_Eos_0001/Demo_WB_Unknown_2019-05-16_10-53-08_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190516_DH_WB_Eos_0001/Demo_WB_Unknown_2019-05-16_10-55-48_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190516_DH_WB_Eos_0001/Demo_WB_Unknown_2019-05-16_11-05-07_CK_Capture_3.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190516_DH_WB_Eos_0001/Demo_WB_Unknown_2019-05-16_11-08-38_CK_Capture_4.seg",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Lymphocytes/190516_DH_WB_Lym_0001/Demo_WB_Unknown_2019-05-16_12-04-19_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Lymphocytes/190516_DH_WB_Lym_0001/Demo_WB_Unknown_2019-05-16_12-08-15_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Lymphocytes/190516_DH_WB_Lym_0001/Demo_WB_Unknown_2019-05-16_12-11-33_CK_Capture_3.seg",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Monocytes/190522_DH_WB_Mon_0001/Demo_WB_Unknown_2019-05-22_12-53-10_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Monocytes/190522_DH_WB_Mon_0001/Demo_WB_Unknown_2019-05-22_12-57-01_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Monocytes/190522_DH_WB_Mon_0001/Demo_WB_Unknown_2019-05-22_13-00-58_CK_Capture_3.seg",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Neutrophils/190516_DH_WB_Neu_0001/Demo_WB_Unknown_2019-05-16_13-11-52_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Neutrophils/190516_DH_WB_Neu_0001/Demo_WB_Unknown_2019-05-16_13-14-57_CK_Capture_3.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Neutrophils/190516_DH_WB_Neu_0001/Demo_WB_Unknown_2019-05-16_13-17-55_CK_Capture_4.seg",
                                ],
                        },
           "donorB": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190516_DH_WB_Eos_0002/Demo_WB_Unknown_2019-05-16_11-22-05_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190516_DH_WB_Eos_0002/Demo_WB_Unknown_2019-05-16_11-25-26_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190516_DH_WB_Eos_0002/Demo_WB_Unknown_2019-05-16_11-29-13_CK_Capture_3.seg",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Lymphocytes/190516_DH_WB_Lym_0002/Demo_WB_Unknown_2019-05-16_12-28-37_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Lymphocytes/190516_DH_WB_Lym_0002/Demo_WB_Unknown_2019-05-16_12-32-45_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Lymphocytes/190516_DH_WB_Lym_0002/Demo_WB_Unknown_2019-05-16_12-36-09_CK_Capture_3.seg",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Monocytes/190522_DH_WB_Mon_0002/Demo_WB_Unknown_2019-05-22_13-12-52_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Monocytes/190522_DH_WB_Mon_0002/Demo_WB_Unknown_2019-05-22_13-16-05_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Monocytes/190522_DH_WB_Mon_0002/Demo_WB_Unknown_2019-05-22_13-19-31_CK_Capture_3.seg",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Neutrophils/190516_DH_WB_Neu_0002/Demo_WB_Unknown_2019-05-16_13-25-19_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Neutrophils/190516_DH_WB_Neu_0002/Demo_WB_Unknown_2019-05-16_13-27-46_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Neutrophils/190516_DH_WB_Neu_0002/Demo_WB_Unknown_2019-05-16_13-31-06_CK_Capture_3.seg",
                                ],
                           "wbc_healthy": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/wbc_healthy/RS_2_11_2019-05-28_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/wbc_healthy/RS_2_11_2019-05-28_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/wbc_healthy/RS_2_11_2019-05-28_Capture_3.seg",
                                ],
                        },
           "donorC": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190516_DH_WB_Eos_0003/Demo_WB_Unknown_2019-05-16_11-39-15_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190516_DH_WB_Eos_0003/Demo_WB_Unknown_2019-05-16_11-42-45_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190516_DH_WB_Eos_0003/Demo_WB_Unknown_2019-05-16_11-48-47_CK_Capture_3.seg",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Lymphocytes/190516_DH_WB_Lym_0003/Demo_WB_Unknown_2019-05-16_12-47-24_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Lymphocytes/190516_DH_WB_Lym_0003/Demo_WB_Unknown_2019-05-16_12-52-18_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Lymphocytes/190516_DH_WB_Lym_0003/Demo_WB_Unknown_2019-05-16_12-55-32_CK_Capture_3.seg",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Monocytes/190522_DH_WB_Mon_0003/Demo_WB_Unknown_2019-05-22_13-27-50_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Monocytes/190522_DH_WB_Mon_0003/Demo_WB_Unknown_2019-05-22_13-30-21_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Monocytes/190522_DH_WB_Mon_0003/Demo_WB_Unknown_2019-05-22_13-32-53_CK_Capture_3.seg",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Neutrophils/190516_DH_WB_Neu_0003/Demo_WB_Unknown_2019-05-16_13-41-02_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Neutrophils/190516_DH_WB_Neu_0003/Demo_WB_Unknown_2019-05-16_13-45-26_CK_Capture_2.seg",
                                ],
                        },
           "unknown": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190520_DH_WB_Eos_0004/Demo_WB_Unknown_2019-05-20_10-51-24_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190520_DH_WB_Eos_0004/Demo_WB_Unknown_2019-05-20_10-56-18_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190520_DH_WB_Eos_0004/Demo_WB_Unknown_2019-05-20_11-00-31_CK_Capture_3.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190520_DH_WB_Eos_0005/Demo_WB_Unknown_2019-05-20_11-09-31_CK_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190520_DH_WB_Eos_0005/Demo_WB_Unknown_2019-05-20_11-14-03_CK_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/Eosinophils/190520_DH_WB_Eos_0005/Demo_WB_Unknown_2019-05-20_11-21-04_CK_Capture_3.seg",
                                ], 
                           "wbc_healthy": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/wbc_healthy/RS_8_13_2019-05-28_Capture_4.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/wbc_healthy/RS_8_13_2019-05-28_Capture_5.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/wbc_healthy/RS_8_13_2019-05-28_Capture_6.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/wbc_healthy/RS_3_15_2019-05-28_Capture_7.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/wbc_healthy/RS_3_15_2019-05-28_Capture_8.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/wbc_healthy/RS_3_15_2019-05-28_Capture_9.seg",
                                ], 
                        },
        },
    
    "singapore": 
        {
           "donorD": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/Eosinophils/Demo_WB_philipp_2023-12-05_07-05-11_K_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/Eosinophils/Demo_WB_philipp_2023-12-05_07-08-44_K_Capture_2.seg",
                                ], 
                           "eos_lysed": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/Eosinophil_Lysis/Demo_WB_philipp_2023-12-05_07-20-23_K_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/Eosinophil_Lysis/Demo_WB_philipp_2023-12-05_07-23-51_K_Capture_2.seg",
                                ], 
                           "t_cell": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/T_Cells/Demo_WB_philipp_2023-12-05_08-43-50_K_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/T_Cells/Demo_WB_philipp_2023-12-05_08-59-35_K_Capture_2.seg",
                                ], 
                           "t_cell_lysed": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/T_Cells_Lysis/Demo_WB_philipp_2023-12-05_09-23-37_K_Capture_2.seg",
                                ],
                           "b_cell": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/B_Cells/Demo_WB_philipp_2023-12-05_08-02-32_K_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/B_Cells/Demo_WB_philipp_2023-12-05_08-06-25_K_Capture_2.seg",
                                ],
                           "b_cell_lysed": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/B_Cells_Lysis/Demo_WB_philipp_2023-12-05_08-19-29_K_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/B_Cells_Lysis/Demo_WB_philipp_2023-12-05_08-24-19_K_Capture_2.seg",
                                ],
                           "neu": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/Neutrophils/Demo_WB_philipp_2023-12-05_04-54-50_K_Capture_1.seg",
                                ],
                           "neu_lysed": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/Neutrophil_lysis/Demo_WB_philipp_2023-12-05_04-46-26_K_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/experiments_6December_blood_philipp/Neutrophil_lysis/Demo_WB_philipp_2023-12-05_06-02-49_K_Capture_2.seg",
                                ],
                        },
          "unknown": 
                        {
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/SGP_olderStuff/Monocytes/SGP_unknown_2023-07-27_08-35-20_K_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/SGP_olderStuff/Monocytes/SGP_unknown_2023-07-27_08-39-39_K_Capture_2.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/SGP_olderStuff/Monocytes/SGP_unknown_2023-07-27_08-43-55_K_Capture_3.seg",
                                ],
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/SGP_olderStuff/Neutrophils/SGP_neutrophils_healthyDonor_2023-09-14_08-44-40_KD_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/SGP_olderStuff/Neutrophils/SGP_neutrophils_healthyDonor_2023-09-14_08-48-02_KD_Capture_2.seg",
                                ],
                            "t_cell":
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/SGP_olderStuff/T-Cells/TCells_SGP_unknown_2023-04-11_08-53-17_K_Capture_4.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/SGP_olderStuff/T-Cells/TCells_SGP_unknown_2023-04-11_08-58-34_K_Capture_5.seg",
                                ],
                            "b_cell": 
                                [
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/SGP_olderStuff/B-Cells/BCells_SGP_unknown_2023-04-11_09-40-50_K_Capture_1.seg",
                                    "/media/storage/ga94zuw/datasets/seg_files/SGP/SGP_olderStuff/B-Cells/BCells_SGP_unknown_2023-04-11_09-46-46_K_Capture_2.seg",
                                ],
                        }                        
        }
    
}



cell_file_filter_indices = {
    "munich": 
        {
           "donorA": 
                        {
                            "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0001_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0001_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0001_cap3_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0001_cap4_filter_indices.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/lym_donor_0001_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/lym_donor_0001_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/lym_donor_0001_cap3_filter_indices.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/mon_donor_0001_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/mon_donor_0001_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/mon_donor_0001_cap3_filter_indices.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/neu_donor_0001_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/neu_donor_0001_cap3_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/neu_donor_0001_cap4_filter_indices.pkl",
                                ],
                        },
           "donorB": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0002_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0002_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0002_cap3_filter_indices.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/lym_donor_0002_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/lym_donor_0002_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/lym_donor_0002_cap3_filter_indices.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/mon_donor_0002_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/mon_donor_0002_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/mon_donor_0002_cap3_filter_indices.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/neu_donor_0002_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/neu_donor_0002_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/neu_donor_0002_cap3_filter_indices.pkl",
                                ],
                           "wbc_healthy": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich/wbc_healthy_capture_1.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich/wbc_healthy_capture_2.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich/wbc_healthy_capture_3.pkl",
                                ],
                        },
           "donorC": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0003_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0003_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0003_cap3_filter_indices.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/lym_donor_0003_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/lym_donor_0003_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/lym_donor_0003_cap3_filter_indices.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/mon_donor_0003_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/mon_donor_0003_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/mon_donor_0003_cap3_filter_indices.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/neu_donor_0003_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/neu_donor_0003_cap2_filter_indices.pkl",
                                ],
                        },
           "unknown": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0004_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0004_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0004_cap3_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0005_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0005_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich/eos_donor_0005_cap3_filter_indices.pkl",
                                ], 
                           "wbc_healthy": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich/wbc_healthy_capture_4.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich/wbc_healthy_capture_5.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich/wbc_healthy_capture_6.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich/wbc_healthy_capture_7.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich/wbc_healthy_capture_8.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich/wbc_healthy_capture_9.pkl",
                                ], 
                        },
        },
    
    "singapore": 
        {
           "donorD": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/eos_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/eos_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ], 
                           "eos_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/eos_lysed_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/eos_lysed_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ], 
                           "t_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/tcell_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/tcell_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ], 
                           "t_cell_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/tcell_lysed_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ],
                           "b_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/bcell_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/bcell_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ],
                           "b_cell_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/bcell_lysed_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/bcell_lysed_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ],
                           "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/neu_donor_philipp_sgp_cap1_filter_indices.pkl",
                                ],
                           "neu_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/neu_lysed_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp/neu_lysed_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ],
                        },
          "unknown": 
                        {
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors/mon_unknown_donor_oldSGPfiles_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors/mon_unknown_donor_oldSGPfiles_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors/mon_unknown_donor_oldSGPfiles_cap3_filter_indices.pkl",
                                ],
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors/neu_unknown_donor_oldSGPfiles_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors/neu_unknown_donor_oldSGPfiles_cap2_filter_indices.pkl",
                                ],
                            "t_cell":
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors/t-cell_unknown_donor_oldSGPfiles_cap4_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors/t-cell_unknown_donor_oldSGPfiles_cap5_filter_indices.pkl",
                                ],
                            "b_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors/b-cell_unknown_donor_oldSGPfiles_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors/b-cell_unknown_donor_oldSGPfiles_cap2_filter_indices.pkl",
                                ],
                        }                        
        }
    
}


cell_file_filter_indices_UPDATED_FEATURES = {
    "munich": 
        {
           "donorA": 
                        {
                            "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap3_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap4_filter_indices.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/lym_donor_0001_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/lym_donor_0001_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/lym_donor_0001_cap3_filter_indices.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/mon_donor_0001_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/mon_donor_0001_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/mon_donor_0001_cap3_filter_indices.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/neu_donor_0001_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/neu_donor_0001_cap3_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/neu_donor_0001_cap4_filter_indices.pkl",
                                ],
                        },
           "donorB": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0002_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0002_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0002_cap3_filter_indices.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/lym_donor_0002_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/lym_donor_0002_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/lym_donor_0002_cap3_filter_indices.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/mon_donor_0002_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/mon_donor_0002_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/mon_donor_0002_cap3_filter_indices.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/neu_donor_0002_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/neu_donor_0002_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/neu_donor_0002_cap3_filter_indices.pkl",
                                ],
                           "wbc_healthy": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_1.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_2.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_3.pkl",
                                ],
                        },
           "donorC": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0003_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0003_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0003_cap3_filter_indices.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/lym_donor_0003_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/lym_donor_0003_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/lym_donor_0003_cap3_filter_indices.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/mon_donor_0003_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/mon_donor_0003_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/mon_donor_0003_cap3_filter_indices.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/neu_donor_0003_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/neu_donor_0003_cap2_filter_indices.pkl",
                                ],
                        },
           "unknown": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0004_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0004_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0004_cap3_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0005_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0005_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SFC_Munich_UPDATED_FEATURES/eos_donor_0005_cap3_filter_indices.pkl",
                                ], 
                           "wbc_healthy": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_4.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_5.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_6.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_7.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_8.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_9.pkl",
                                ], 
                        },
        },
    
    "singapore": 
        {
           "donorD": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/eos_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/eos_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ], 
                           "eos_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/eos_lysed_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/eos_lysed_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ], 
                           "t_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/tcell_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/tcell_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ], 
                           "t_cell_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/tcell_lysed_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ],
                           "b_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/bcell_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/bcell_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ],
                           "b_cell_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/bcell_lysed_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/bcell_lysed_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ],
                           "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/neu_donor_philipp_sgp_cap1_filter_indices.pkl",
                                ],
                           "neu_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/neu_lysed_donor_philipp_sgp_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_donor_Philipp_UPDATED_FEATURES/neu_lysed_donor_philipp_sgp_cap2_filter_indices.pkl",
                                ],
                        },
          "unknown": 
                        {
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors_UPDATED_FEATURES/mon_unknown_donor_oldSGPfiles_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors_UPDATED_FEATURES/mon_unknown_donor_oldSGPfiles_cap2_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors_UPDATED_FEATURES/mon_unknown_donor_oldSGPfiles_cap3_filter_indices.pkl",
                                ],
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors_UPDATED_FEATURES/neu_unknown_donor_oldSGPfiles_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors_UPDATED_FEATURES/neu_unknown_donor_oldSGPfiles_cap2_filter_indices.pkl",
                                ],
                            "t_cell":
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors_UPDATED_FEATURES/t-cell_unknown_donor_oldSGPfiles_cap4_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors_UPDATED_FEATURES/t-cell_unknown_donor_oldSGPfiles_cap5_filter_indices.pkl",
                                ],
                            "b_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors_UPDATED_FEATURES/b-cell_unknown_donor_oldSGPfiles_cap1_filter_indices.pkl",
                                    "/media/storage/ga94zuw/saved_filter_indices/SGP_older_unknownDonors_UPDATED_FEATURES/b-cell_unknown_donor_oldSGPfiles_cap2_filter_indices.pkl",
                                ],
                        }                        
        }
    
}




cell_file_celltypes = {
    "munich": 
        {
           "donorA": 
                        {
                            "eos": 
                                [
                                    "eos",
                                    "eos",
                                    "eos",
                                    "eos",
                                ], 
                            "lym": 
                                [
                                    "lym",
                                    "lym",
                                    "lym",
                                ], 
                            "mon": 
                                [
                                    "mon",
                                    "mon",
                                    "mon",
                                ], 
                            "neu": 
                                [
                                    "neu",
                                    "neu",
                                    "neu",
                                ],
                        },
           "donorB": 
                        {
                           "eos": 
                                [
                                    "eos",
                                    "eos",
                                    "eos",
                                ], 
                            "lym": 
                                [
                                    "lym",
                                    "lym",
                                    "lym",
                                ], 
                            "mon": 
                                [
                                    "mon",
                                    "mon",
                                    "mon",
                                ], 
                            "neu": 
                                [
                                    "neu",
                                    "neu",
                                    "neu",
                                ],
                           "wbc_healthy": 
                                [
                                    "wbc_healthy",
                                    "wbc_healthy",
                                    "wbc_healthy",
                                ],
                        },
           "donorC": 
                        {
                           "eos": 
                                [
                                    "eos",
                                    "eos",
                                    "eos",
                                ], 
                            "lym": 
                                [
                                    "lym",
                                    "lym",
                                    "lym",
                                ], 
                            "mon": 
                                [
                                    "mon",
                                    "mon",
                                    "mon",
                                ], 
                            "neu": 
                                [
                                    "neu",
                                    "neu",
                                ],
                        },
           "unknown": 
                        {
                           "eos": 
                                [
                                    "eos",
                                    "eos",
                                    "eos",
                                    "eos",
                                    "eos",
                                    "eos",
                                ], 
                           "wbc_healthy": 
                                [
                                    "wbc_healthy",
                                    "wbc_healthy",
                                    "wbc_healthy",
                                    "wbc_healthy",
                                    "wbc_healthy",
                                    "wbc_healthy",
                                ], 
                        },
        },
    
    "singapore": 
        {
           "donorD": 
                        {
                           "eos": 
                                [
                                    "eos",
                                    "eos",
                                ], 
                           "eos_lysed": 
                                [
                                    "eos",
                                    "eos",
                                ], 
                           "t_cell": 
                                [
                                    "lym",
                                    "lym",
                                ], 
                           "t_cell_lysed": 
                                [
                                    "lym",
                                ],
                           "b_cell": 
                                [
                                    "lym",
                                    "lym",
                                ],
                           "b_cell_lysed": 
                                [
                                    "lym",
                                    "lym",
                                ],
                           "neu": 
                                [
                                    "neu",
                                ],
                           "neu_lysed": 
                                [
                                    "neu",
                                    "neu",
                                ],
                        },
          "unknown": 
                        {
                            "mon": 
                                [
                                    "mon",
                                    "mon",
                                    "mon",
                                ],
                            "neu": 
                                [
                                    "neu",
                                    "neu",
                                ],
                            "t_cell":
                                [
                                    "lym",
                                    "lym",
                                ],
                            "b_cell": 
                                [
                                    "lym",
                                    "lym",
                                ],
                        }                        
        }
    
}




# updated morph features
morph_features = {
    "munich": 
        {
           "donorA": 
                        {
                            "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap3_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap4_morph_features.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0001_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0001_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0001_cap3_morph_features.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0001_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0001_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0001_cap3_morph_features.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0001_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0001_cap3_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0001_cap4_morph_features.pkl",
                                ],
                        },
           "donorB": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0002_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0002_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0002_cap3_morph_features.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0002_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0002_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0002_cap3_morph_features.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0002_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0002_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0002_cap3_morph_features.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0002_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0002_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0002_cap3_morph_features.pkl",
                                ],
                           "wbc_healthy": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_3_morph_features.pkl",
                                ],
                        },
           "donorC": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0003_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0003_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0003_cap3_morph_features.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0003_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0003_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0003_cap3_morph_features.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0003_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0003_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0003_cap3_morph_features.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0003_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0003_cap2_morph_features.pkl",
                                ],
                        },
           "unknown": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0004_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0004_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0004_cap3_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0005_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0005_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0005_cap3_morph_features.pkl",
                                ], 
                           "wbc_healthy": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_4_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_5_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_6_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_7_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_8_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_9_morph_features.pkl",
                                ], 
                        },
        },
    
    "singapore": 
        {
           "donorD": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/eos_donor_philipp_sgp_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/eos_donor_philipp_sgp_cap2_morph_features.pkl",
                                ], 
                           "eos_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/eos_lysed_donor_philipp_sgp_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/eos_lysed_donor_philipp_sgp_cap2_morph_features.pkl",
                                ], 
                           "t_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/tcell_donor_philipp_sgp_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/tcell_donor_philipp_sgp_cap2_morph_features.pkl",
                                ], 
                           "t_cell_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/tcell_lysed_donor_philipp_sgp_cap2_morph_features.pkl",
                                ],
                           "b_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/bcell_donor_philipp_sgp_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/bcell_donor_philipp_sgp_cap2_morph_features.pkl",
                                ],
                           "b_cell_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/bcell_lysed_donor_philipp_sgp_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/bcell_lysed_donor_philipp_sgp_cap2_morph_features.pkl",
                                ],
                           "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/neu_donor_philipp_sgp_cap1_morph_features.pkl",
                                ],
                           "neu_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/neu_lysed_donor_philipp_sgp_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/neu_lysed_donor_philipp_sgp_cap2_morph_features.pkl",
                                ],
                        },
          "unknown": 
                        {
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/mon_unknown_donor_oldSGPfiles_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/mon_unknown_donor_oldSGPfiles_cap2_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/mon_unknown_donor_oldSGPfiles_cap3_morph_features.pkl",
                                ],
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/neu_unknown_donor_oldSGPfiles_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/neu_unknown_donor_oldSGPfiles_cap2_morph_features.pkl",
                                ],
                            "t_cell":
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/t-cell_unknown_donor_oldSGPfiles_cap4_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/t-cell_unknown_donor_oldSGPfiles_cap5_morph_features.pkl",
                                ],
                            "b_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/b-cell_unknown_donor_oldSGPfiles_cap1_morph_features.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/b-cell_unknown_donor_oldSGPfiles_cap2_morph_features.pkl",
                                ],
                        }                        
        }
    
}


# updated glcm features
glcm_features = {
    "munich": 
        {
           "donorA": 
                        {
                            "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap3_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0001_cap4_morph_features_glcm.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0001_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0001_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0001_cap3_morph_features_glcm.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0001_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0001_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0001_cap3_morph_features_glcm.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0001_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0001_cap3_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0001_cap4_morph_features_glcm.pkl",
                                ],
                        },
           "donorB": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0002_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0002_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0002_cap3_morph_features_glcm.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0002_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0002_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0002_cap3_morph_features_glcm.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0002_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0002_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0002_cap3_morph_features_glcm.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0002_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0002_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0002_cap3_morph_features_glcm.pkl",
                                ],
                           "wbc_healthy": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_3_morph_features_glcm.pkl",
                                ],
                        },
           "donorC": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0003_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0003_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0003_cap3_morph_features_glcm.pkl",
                                ], 
                            "lym": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0003_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0003_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/lym_donor_0003_cap3_morph_features_glcm.pkl",
                                ], 
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0003_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0003_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/mon_donor_0003_cap3_morph_features_glcm.pkl",
                                ], 
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0003_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/neu_donor_0003_cap2_morph_features_glcm.pkl",
                                ],
                        },
           "unknown": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0004_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0004_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0004_cap3_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0005_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0005_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SFC_Munich_UPDATED_FEATURES/eos_donor_0005_cap3_morph_features_glcm.pkl",
                                ], 
                           "wbc_healthy": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_4_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_5_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_6_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_7_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_8_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/WBC_Healthy_Munich_UPDATED_FEATURES/wbc_healthy_capture_9_morph_features_glcm.pkl",
                                ], 
                        },
        },
    
    "singapore": 
        {
           "donorD": 
                        {
                           "eos": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/eos_donor_philipp_sgp_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/eos_donor_philipp_sgp_cap2_morph_features_glcm.pkl",
                                ], 
                           "eos_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/eos_lysed_donor_philipp_sgp_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/eos_lysed_donor_philipp_sgp_cap2_morph_features_glcm.pkl",
                                ], 
                           "t_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/tcell_donor_philipp_sgp_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/tcell_donor_philipp_sgp_cap2_morph_features_glcm.pkl",
                                ], 
                           "t_cell_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/tcell_lysed_donor_philipp_sgp_cap2_morph_features_glcm.pkl",
                                ],
                           "b_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/bcell_donor_philipp_sgp_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/bcell_donor_philipp_sgp_cap2_morph_features_glcm.pkl",
                                ],
                           "b_cell_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/bcell_lysed_donor_philipp_sgp_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/bcell_lysed_donor_philipp_sgp_cap2_morph_features_glcm.pkl",
                                ],
                           "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/neu_donor_philipp_sgp_cap1_morph_features_glcm.pkl",
                                ],
                           "neu_lysed": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/neu_lysed_donor_philipp_sgp_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_donor_Philipp_UPDATED_FEATURES/neu_lysed_donor_philipp_sgp_cap2_morph_features_glcm.pkl",
                                ],
                        },
          "unknown": 
                        {
                            "mon": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/mon_unknown_donor_oldSGPfiles_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/mon_unknown_donor_oldSGPfiles_cap2_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/mon_unknown_donor_oldSGPfiles_cap3_morph_features_glcm.pkl",
                                ],
                            "neu": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/neu_unknown_donor_oldSGPfiles_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/neu_unknown_donor_oldSGPfiles_cap2_morph_features_glcm.pkl",
                                ],
                            "t_cell":
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/t-cell_unknown_donor_oldSGPfiles_cap4_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/t-cell_unknown_donor_oldSGPfiles_cap5_morph_features_glcm.pkl",
                                ],
                            "b_cell": 
                                [
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/b-cell_unknown_donor_oldSGPfiles_cap1_morph_features_glcm.pkl",
                                    "/media/storage/ga94zuw/saved_morphological_features/SGP_older_unknownDonors_UPDATED_FEATURES/b-cell_unknown_donor_oldSGPfiles_cap2_morph_features_glcm.pkl",
                                ],
                        }                        
        }
    
}
